### ISSUE TITLE
iframe placeholder box after you view the source of the content

### ISSUE THREAD

**Issue by aapljack** [fonini/ckeditor-youtube-plugin#27]
When you add a youtube video to the content in ckeditor, the video is displayed in the editor.  Once you hit the 'Source' button to see the source of the content and return to the WYSIWYG editor, the video is represented by a box that says 'iframe' instead of the video. It would be great if, when you return to the WYSIWYG editor, that it still displays the video.

![ckeditor](https://cloud.githubusercontent.com/assets/630399/4156674/b8109c64-3476-11e4-82cd-0d5e5499fe9d.png)

**Comment by indianazhao** [comment]
Hi @aapljack , could you please share how you solve the issue? Thank you.

**Comment by aapljack** [comment]
@indianazhao We ended up building a custom solution for videos and using a limited number of the ckeditor options for text editing.

**Comment by indianazhao** [comment]
@aapljack , ya, I found that the issue is gone once I use the standard version instead of full one! Thanks a lot!

**Comment by adinan-cenci** [comment]
Hello. I am getting this error when I install the [IFrame Dialog Field](https://ckeditor.com/cke4/addon/iframedialog) plugin.

Do you know how to have both plugins working?
