### ISSUE TITLE
Guide addition

### ISSUE THREAD

**Issue by subdesign** [fonini/ckeditor-youtube-plugin#30]
You can add an info if someone use custom toolbar configuration, he has to add 'Youtube' into the config array, because by default the icon doesn't appear in the toolbar. 
Eg.:

```js
config.toolbar = [		
        ...
		{ name: 'others', items: [ 'Youtube' ] },		
	];
```

**Comment by mattlangtree** [comment]
+1 for adding this to your setup guide as this was a crucial part of getting your plugin to work for me.
