### ISSUE TITLE
Make responsive resets itself

### ISSUE THREAD

**Issue by 0x1ad2** [fonini/ckeditor-youtube-plugin#33]
Dear Fonini,

If I select the ```Make Responsive (ignore width and height, fit to width)``` option in de ```Embed Youtube Video``` dialog it inserts a video with ```width:100%;``` so that's good but when I save my page and load the content in CKeditor for a second time the width get resetted to the defined value.

To illustrate it I've made a screencap

![Screencap](http://gyazo.com/e2f21730bef902f39021a90649efa5f2.gif)

*Note: the refresh is pretty fast so you might not notice it*

**Comment by 0x1ad2** [comment]
@fonini any progress on this issue?

**Comment by fonini** [comment]
Hi Dennis, unfortunatelly I do not have time to look into this issue right now :(

**Comment by 0x1ad2** [comment]
Ah that's unfortunate is there a way we could fix this issue ourselves?

**Comment by fonini** [comment]
I really don't know how to fix this issue. You can try to read the "style" attribute when you're editing the video and ignore the default width and height. I think that involves lots of code changes.

**Comment by 0x1ad2** [comment]
Could I write some JavaScript for that?

**Comment by fonini** [comment]
Found the problem! When you check the "Responsive video" option, the video is wrapped by a DIV. CKEditor removes that div. A quick fix would by you set ````config.allowedContent = true;```` on your config.js file. 
I'll look at my ACF rules to prevent this.

**Comment by 0x1ad2** [comment]
Ah that worked thanks a lot and good luck fixing the ACF rules!

**Comment by GerrGIT** [comment]
It can be fixed by changing allowedContent rules on line 14 of plugin.js into: 'div{*}; iframe{*}[!width,!height,!src,!frameborder,!allowfullscreen]; object param[*]'
I'm new into Git, that's why I did not pull/push/commit whatever it myself and leave this comment instead :).
