### ISSUE TITLE
Disabling the change of settings

### ISSUE THREAD

**Issue by Danchello** [fonini/ckeditor-youtube-plugin#35]
Is there a way to disable changing such setting as autoplay and width/heigh?

I use CKEDITOR for regular users which could add a youtube video, but I don't want them to break the design or set the autoplay setting.

Thanks in advance/

**Comment by Vova11** [comment]
Hi Danchello, 

Did you find out how to hide  e.g. txtEmbed of txtWidth,... from the youtubePlugin window?
Somehow I can not disable these settings. When I put youtubeTab.remove('txtEmbed'); to ckeditor config.js I get following error in console ....Uncaught TypeError: Cannot read property 'disable' of undefined 
Thanks in advance for any advice.

**Comment by fonini** [comment]
Which fields you would like to disable?

**Comment by master-bob** [comment]
We would like the the ability to disable the old embed code field and the responsive field.

**Comment by fonini** [comment]
Added in the last version. Please see the instructions in [README](https://github.com/fonini/ckeditor-youtube-plugin/blob/master/README.md). Feel free to get in touch.
