### ISSUE TITLE
Add class to wrapper div

### ISSUE THREAD

**Issue by asrob** [fonini/ckeditor-youtube-plugin#37]
Hi!

The wrapper div has not any classes that's why I can't use it via CSS easily. Can you add a class like "youtube-embed" to that div?

**Comment by fonini** [comment]
Hi! I've added the class ````youtube-embed-wrapper```` to the responsive div.

**Comment by asrob** [comment]
Cool, thanks! :)

When do you plan to release a new version? :)

**Comment by fonini** [comment]
Just published on the CKEditor Plugins page.
