### ISSUE TITLE
Edit Youtube video embed codes in WYSIWYG

### ISSUE THREAD

**Issue by StevenFlecha** [fonini/ckeditor-youtube-plugin#45]
Hey,

Is this plugin able to replace a youtube video existing on the page (editable content of course) either via:

```
<div contenteditable="true">
 <iframe src='youtubeurl'.... ></iframe>
</div>
```

or via 

```
<iframe contenteditable='true' src='youtubeurl'.... ></iframe>
```

? 
I have a plugin called 'Youtube' from CKeditor site but that one is not able to do this. Currently I'm using the standard iframe plugin but I'd like to limited it to just youtube videos not just any iframe url.

Thanks

**Comment by fonini** [comment]
Hi, the plugin from CKEditor site is this one. I'm sorry, at the moment, you can paste embed code from any site.
