### ISSUE TITLE
Video Poster disappears

### ISSUE THREAD

**Issue by radiovisual** [fonini/ckeditor-youtube-plugin#46]
After I use `ckeditor-youtube-plugin`, I immediately see the typical video poster to the video I am embedding in the ckeditor pane:

![before](https://cloud.githubusercontent.com/assets/5614571/12125117/6b00e122-b3e1-11e5-9ad1-b803f8082ce0.png)

**But** after I toggle the `Source` view (using the button shown at the top-left of my screenshots), as soon as I toggle out of Source View, then all I see is this IFRAME box:

![after](https://cloud.githubusercontent.com/assets/5614571/12125165/b3a0dacc-b3e1-11e5-8b36-aa8359ba49ca.png)

This behavior also happens after I save the content of the ckeditor to the database and review the content. 

So can this be fixed, or is this a limitation of the ckeditor environment?

I am using version `2.1.0` of this plugin.

**Comment by Trupal00p** [comment]
It seems that the built in iframe plugin is acting first so you see the place holder instead of the video.
if you disable the iframe plugin you see the video as if you had just inserted it:

```javascript
config.removePlugins = 'iframe';
```

Would be nice if there was a way to only have this happen to youtube iframes, don't know ckeditor well enough to know if that's possible.

**Comment by radiovisual** [comment]
Thanks @Trupal00p . That was the solution. I am using Python/Django, so I was able to add this to my settings.py file:

```python
CKEDITOR_CONFIGS = {
        # ....
        'removePlugins' : ','.join(
            [
                'iframe',
            ]),
    }
```

Which is essentially the same as calling `config.removePlugins = 'iframe';`

Once I did that, the youtube posters appear normally. 

:+1:
