### ISSUE TITLE
Can't load youtube iframe in wysiwyg or preview

### ISSUE THREAD

**Issue by henry-geronimo** [fonini/ckeditor-youtube-plugin#58]
I can add the video trough the plugin, the iframe is inserted. but it won't load. I get this error

"Refused to frame 'https://www.youtube.com/embed/XXXXX' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback."

Any idea ? have i missed something ?

**Comment by fonini** [comment]
I think that is a problem not related with the plugin.
Can you check if you have a "Content-Security-Policy" header in your page?

**Comment by henry-geronimo** [comment]
I don't have any Content-Security-Policy inside my html page. It just comes out of nowhere.
Anyway I can't load any iframe even outside the wysiwyg so it must not be an issue with this plugin.
Sorry for inconvenience
