### ISSUE TITLE
autoplay bugs

### ISSUE THREAD

**Issue by kstmasa** [fonini/ckeditor-youtube-plugin#69]
Hello

in the allowedContent:

`
editor.addCommand('youtube', new CKEDITOR.dialogCommand('youtube', {
				allowedContent: 'div{*}(*); iframe{*}[!width,!height,!src,!frameborder,!allowfullscreen]; object param[*]; a[*]; img[*]'
			}));
`

It needs to import "!allow" to ` iframe{*}[!width,!height,!src,!frameborder,!allowfullscreen] `

And It can revise content that it has selected "autoplay" checkbox.

And allow="autoplay" won't disappear in the iframe

Thank you.

Input Content:
![image](https://user-images.githubusercontent.com/16588318/44834245-265a6c00-ac63-11e8-8344-680572c0c89f.png)

Output Content:
![image](https://user-images.githubusercontent.com/16588318/44834280-425e0d80-ac63-11e8-9d5a-9542acb93c86.png)

**Comment by fonini** [comment]
Fixed. Thanks!
