### ISSUE TITLE
Publish Tag & Release for 2.1.15

### ISSUE THREAD

**Issue by MRoci** [fonini/ckeditor-youtube-plugin#90]
First of all thank you very much for your efforts in this useful project.

I was wondering if it was possible for you to publish the tag and the release artifacts for version  `2.1.15` as the latest tag is `2.1.13` and the latest github release is `2.1.9`.

Maybe Github Actions could be added to automate this process in the future, if you agreed I could help you deal with it

**Comment by fonini** [comment]
Hi @MRoci!

I'll appreciate very much if you can help me with the Github Actions.

I'm into Golang right now, so I'm only accepting PR's for this project.

Thanks in advance!
